/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#e6e8ea",
        "on-surface": "#191c1e",
        "secondary-fixed-dim": "#adc6ff",
        "sage-blue-gradient-start": "#1E293B",
        "surface-container": "#eceef0",
        "primary": "#000000",
        "surface-container-low": "#f2f4f6",
        "error-container": "#ffdad6",
        "surface-variant": "#e0e3e5",
        "sage-blue-gradient-end": "#0F172A",
        "secondary-fixed": "#d8e2ff",
        "on-primary": "#ffffff",
        "on-primary-container": "#7c839b",
        "secondary": "#0058be",
        "outline": "#76777d",
        "surface-dim": "#d8dadc",
        "primary-fixed": "#dae2fd",
        "on-primary-fixed-variant": "#3f465c",
        "success-emerald": "#10B981",
        "surface-container-highest": "#e0e3e5",
        "inverse-surface": "#2d3133",
        "on-secondary": "#ffffff",
        "on-surface-variant": "#45464d",
        "outline-variant": "#c6c6cd",
        "on-error-container": "#93000a",
        "on-background": "#191c1e",
        "surface": "#f7f9fb",
        "slate-gray": "#64748B",
        "tertiary": "#000000",
        "on-secondary-container": "#fefcff",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed-variant": "#004395",
        "on-secondary-fixed": "#001a42",
        "on-error": "#ffffff",
        "secondary-container": "#2170e4",
        "primary-fixed-dim": "#bec6e0",
        "on-tertiary-fixed": "#07006c",
        "tertiary-container": "#07006c",
        "inverse-primary": "#bec6e0",
        "surface-bright": "#f7f9fb",
        "inverse-on-surface": "#eff1f3",
        "primary-container": "#131b2e",
        "on-tertiary-fixed-variant": "#2f2ebe",
        "on-tertiary-container": "#7073ff",
        "on-primary-fixed": "#131b2e",
        "error": "#ba1a1a",
        "background": "#f7f9fb",
        "tertiary-fixed": "#e1e0ff",
        "surface-tint": "#565e74",
        "tertiary-fixed-dim": "#c0c1ff",
        "on-tertiary": "#ffffff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "base": "8px",
        "gutter-md": "24px",
        "gutter-sm": "16px",
        "max-content-width": "1280px",
        "margin-mobile": "16px",
        "margin-desktop": "40px"
      },
      fontSize: {
        "headline-xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" }]
      }
    },
  },
  plugins: [],
}
